blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/stritti/nocodb-middleware/discussions
    about: Please ask and answer questions in the Discussions section
